// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWBeXp-E3xsVPngXJ_4c34oJAu-we2bik',
    appId: '1:320022240083:web:cad6688c1d1c29c8f69fa6',
    messagingSenderId: '320022240083',
    projectId: 'anveshakkk',
    authDomain: 'anveshakkk.firebaseapp.com',
    storageBucket: 'anveshakkk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqqS7jX-z35Ew43qD10cfFLBo8nr5ucYA',
    appId: '1:320022240083:android:cbbf09c878ea8d69f69fa6',
    messagingSenderId: '320022240083',
    projectId: 'anveshakkk',
    storageBucket: 'anveshakkk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_z_WJg8Ijaiqgy0g58hBkJjDIRp-sulE',
    appId: '1:320022240083:ios:00f4f8d26978b27bf69fa6',
    messagingSenderId: '320022240083',
    projectId: 'anveshakkk',
    storageBucket: 'anveshakkk.firebasestorage.app',
    iosBundleId: 'com.example.anveshak',
  );

}